#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- clear and reload
reset;
model neos/cart-pendulum-utot.mod;
data neos/cart-pendulum-utot.dat;

#----------- options
option presolve_eps 1e-14;
option solver ipopt;

option log_file 'neos/cart-pendulum-utot.log';
option times 1;
option gentimes 1;
option show_stats 2;
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* script
#----------- problem
problem SCRIPTTEST :
  UTOT,
  t, q, v, a, u, f, I,
  g_des, gdot_des, gddot_des,
  CONA, EOM,
  TPI, IME, POSTQ, POSTV,
  ODE_hK,
  ODE_DEFSTEP,
  ODE_DEFQ, ODE_COLQ, ODE_DEFV, ODE_COLV,
  ODE_DEFTIME, ODE_COLTIME,
  X0, CART_FINAL, PENDULUM_FINAL, VEL_FINAL,
  CART, PENDULUM,
  U_CART, U_PENDULUM,
  T0, TF
;

#----------- solve
solve SCRIPTTEST;
if solve_result != 'solved' then {
  print 'failed!', 'SCRIPTTEST', '--', SCRIPTTEST.result, '--',  SCRIPTTEST.message;
}
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* script!

print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j] > test.out;
print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j] >> test.out;
print {j in 1.._nvars : match(_varname[j], '^u\[') > 0} : j, _varname[j], _var[j] >> test.out;
close test.out;

display _ampl_elapsed_time;
display _ampl_system_time, _ampl_user_time, _ampl_time, _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
