#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- clear and reload
reset;
model neos/five-link-phc-kelly.mod;
data neos/five-link-phc-kelly.dat;

#----------- options
option presolve_eps 1e-14;
option solver ipopt;

option log_file 'neos/five-link-phc-kelly.log';
option times 1;
option gentimes 1;
option show_stats 2;
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* fivelink test
#----------- gait problem
problem FIVELINKTEST :
  UTOT,
  t, q, v, a, u,
  EOM,
  {i1 in PHASES, i2 in CON_F[i1], i3 in PIM_GRID['+'] inter GRID[i1]: i2 <= 2} I[i1, i2, i3],
  {i1 in PHASES, i2 in CON_M[i1], (i3, i4) in PIM: i4 in GRID[i1] and i2 <= 2} POSTV[i1, i2, i3, i4],
  {i1 in PHASES, i2 in CON_F[i1], i3 in GRID[i1]: i2 <= 2} f[i1, i2, i3],
  {i1 in PHASES, i2 in CON_M[i1], i3 in GRID[i1]: i2 <= 2 and i3 < 1} CONQ[i1, i2, i3],
  {i1 in PHASES, i2 in CON_M[i1], i3 in GRID[i1]: i2 <= 2 and i3 < GRID_MAX} CONV[i1, i2, i3],
  {i1 in PHASES, i2 in CON_M[i1], i3 in GRID[i1]: i2 <= 2 and i3 < GRID_MAX} CONA[i1, i2, i3],
  TPI, IME, POSTQ,
  ODE_hK,
  ODE_DEFQ, ODE_COLQ, ODE_DEFV, ODE_COLV,
  ODE_DEFTIME, ODE_COLTIME, ODE_DEFSTEP,
  T0, TF,
  XT, U,
  STANCE_KNEE_EXTENSION, SWING_KNEE_EXTENSION,
  SWING_PRE_POSX, SWING_PRE_POSY, SWING_PRE_VELY, SWING_POST_VELY,
  GAITX
;

#----------- solve
solve FIVELINKTEST;
if solve_result != 'solved' then {
  print 'failed!', 'FIVELINKTEST', '--', FIVELINKTEST.result, '--',  FIVELINKTEST.message;
}
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* fivelink test!

print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j] > neos/five-link-phc-kelly.out;
print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j] >> neos/five-link-phc-kelly.out;
print {j in 1.._nvars : match(_varname[j], '^u\[') > 0} : j, _varname[j], _var[j] >> neos/five-link-phc-kelly.out;
print {j in 1.._nvars : match(_varname[j], '^f\[') > 0} : j, _varname[j], _var[j] >> neos/five-link-phc-kelly.out;
close neos/five-link-phc-kelly.out;

display _ampl_elapsed_time;
display _ampl_system_time, _ampl_user_time, _ampl_time, _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
