#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings
#----------- clear and reload
reset;
model neos/grasp.mod;
data neos/grasp.dat;

#----------- options
option presolve_eps 1e-14;
option solver gurobi;

option log_file 'neos/grasp.log';
option times 1;
option gentimes 1;
option show_stats 2;

option presolve 1;
option gurobi_options 'tech:timing=2';
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* settings!

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* grasp test
#----------- grasp problem
problem GRASPTEST :
  NUM_FINGERS,
  q, v, a, f, c, fingers,
  {i1 in Q, i2 in GRID[0]: i1 <= nm} EOM[1, i1, i2],
  FC_NO_CONTACT, FC_NO_WRENCH, FPC,
  Q_OBJECT, V_OBJECT, A_OBJECT,
  NUM_CONTACTS, FORM_CLOSURE
;

#----------- solve
solve GRASPTEST;
if solve_result != 'solved' then {
  print 'failed!', 'GRASPTEST', '--', GRASPTEST.result, '--',  GRASPTEST.message;
}
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#* grasp test!

print {j in 1.._nvars : match(_varname[j], '^x\[') > 0} : j, _varname[j], _var[j] > neos/grasp.out;
print {j in 1.._nvars : match(_varname[j], '^t\[') > 0} : j, _varname[j], _var[j] >> neos/grasp.out;
print {j in 1.._nvars : match(_varname[j], '^f\[') > 0} : j, _varname[j], _var[j] >> neos/grasp.out;
print {j in 1.._nvars : match(_varname[j], '^g\[') > 0} : j, _varname[j], _var[j] >> neos/grasp.out;
print {j in 1.._nvars : match(_varname[j], '^OSIM_X_c0\[') > 0} : j, _varname[j], _var[j] >> neos/grasp.out;
print {j in 1.._nvars : match(_varname[j], '^c\[') > 0} : j, _varname[j], _var[j] >> neos/grasp.out;
close neos/grasp.out;

display _ampl_elapsed_time;
display _ampl_system_time, _ampl_user_time, _ampl_time, _solve_elapsed_time, _solve_system_time, _solve_user_time, _solve_time;
